### ISSUE TITLE
How I can get the content uri of a file?

### ISSUE THREAD

**Issue by Richi2293** [PatrissolJuns/react-native-audio-video-tools#2]
Hi,

I need to get the content uri of a file to upload it in a server, te method "getDetails" can return also the content uri of the file?

**Comment by PatrissolJuns** [comment]
@Richi2293 No the getDetails method doesn't return the content of uri and it's normal. You already have the uri and to upload it, I'd highly recommend using [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob#user-content-upload-example--dropbox-files-upload-api) since it's very simple to upload a file with it.

**Comment by Richi2293** [comment]
Thanks for the fast response.

I'll tell you my problem, I need to compress the video and then upload it to the server.
I already have the code ready that uploads the video with the uri file and not the path.
So for this I was wondering if there was a way from the file path to have the uri file

**Comment by PatrissolJuns** [comment]
Actually, I don't have a way but maybe you can try looking for it on StackOverFlow. 

By the way, I think that you can change the way you upload files since you don't yet have the means to convert file path to uri. And as I said it's easier with the path since almost all upload libraries use path rather than uri

**Comment by Richi2293** [comment]
Okok thanks 😄
